import { Platform, StyleSheet } from 'react-native'
import { colors, radius, space, type } from '../theme'

// ─── Styles ────────────────────────────────────────────────────

const mono = Platform.OS === 'ios' ? 'Menlo' : 'monospace'

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  statusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.sm,
    paddingHorizontal: space.lg,
    paddingBottom: space.sm,
    backgroundColor: colors.bg,
  },
  statusText: {
    color: colors.textDim,
    fontSize: 12,
    textTransform: 'capitalize',
  },
  contextWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  contextTrack: {
    flex: 1,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.surfaceRaised,
    overflow: 'hidden',
  },
  contextFill: {
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.accent,
  },
  contextText: {
    color: colors.textFaint,
    fontSize: 11,
    fontFamily: mono,
  },
  costText: {
    color: colors.textDim,
    fontSize: 11,
    fontFamily: mono,
  },
  forkBanner: {
    paddingHorizontal: space.lg,
    paddingVertical: space.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  forkBannerText: {
    color: colors.textDim,
    fontSize: 11,
    lineHeight: 15,
  },
  compactBanner: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  queueChip: { alignSelf: 'flex-start', marginBottom: 6, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border },
  queueChipOn: { borderColor: colors.accent, backgroundColor: colors.accentWash },
  queueChipText: { color: colors.textDim, fontSize: 11 },
  queueChipTextOn: { color: colors.accent },
  compactBannerText: { flex: 1 },
  compactAction: { color: colors.accent, fontSize: 11, lineHeight: 15 },
  feedContent: {
    paddingVertical: 10,
    flexGrow: 1,
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    // No counter-flip here. This block renders OUTSIDE the inverted list, so
    // nothing flips it; the scaleY:-1 that used to cancel the list's transform
    // became the thing turning it upside down once it moved out.
  },
  emptyText: {
    color: colors.textFaint,
    fontSize: 13,
    marginTop: space.sm,
  },
  itemBlock: {
    marginHorizontal: space.lg,
    marginVertical: space.sm,
  },
  userRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginHorizontal: space.lg,
    marginTop: space.lg,
    marginBottom: space.xs,
  },
  // The old bubble was near-black navy on near-black: technically present,
  // practically invisible. A lighter raised surface plus a left accent edge
  // reads as "you said this" without shouting.
  userBubble: {
    maxWidth: '82%',
    backgroundColor: colors.surfaceRaised,
    borderLeftWidth: 2,
    borderLeftColor: colors.accent,
    borderTopRightRadius: radius.md,
    borderBottomRightRadius: radius.md,
    borderTopLeftRadius: 3,
    borderBottomLeftRadius: 3,
    paddingHorizontal: space.md,
    paddingVertical: space.sm + 2,
  },
  lightbox: { flex: 1, backgroundColor: 'rgba(0,0,0,0.92)', alignItems: 'center', justifyContent: 'center' },
  lightboxImage: { width: '100%', height: '80%' },
  sentImage: {
    width: 180,
    height: 180,
    borderRadius: radius.sm,
    marginBottom: space.xs,
    backgroundColor: colors.surfaceRaised,
  },
  userText: {
    ...type.bodySm,
    color: colors.text,
  },
  // A message the backend holds: dashed and unfilled, so it reads as not sent yet.
  heldBubble: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderLeftWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.border,
    borderLeftColor: colors.border,
  },
  heldBar: { flexDirection: 'row', alignItems: 'center', gap: space.sm, marginTop: space.sm },
  heldChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: radius.sm,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  heldChipText: { ...type.monoSm, color: colors.textDim },
  heldHint: { flex: 1, ...type.monoSm, color: colors.textFaint },
  heldAction: { padding: 4, borderRadius: radius.sm },
  heldActionDisabled: { opacity: 0.4 },
  deliveryText: {
    marginTop: space.xs,
    ...type.monoSm,
    color: colors.textFaint,
  },
  deliveryFailed: {
    color: colors.red,
  },
  // Prose is the hero: it gets the widest measure and the most contrast, while
  // tool cards below deliberately recede.
  assistantText: {
    ...type.body,
    color: colors.text,
  },
  durationText: {
    marginTop: space.xs,
    ...type.monoSm,
    color: colors.textFaint,
  },
  reasoningText: {
    color: colors.textDim,
    fontSize: 13,
    lineHeight: 19,
    fontStyle: 'italic',
  },
  toggleText: {
    marginTop: 4,
    color: colors.accent,
    fontSize: 12,
  },
  planStreamBox: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    backgroundColor: colors.surface,
  },
  monoText: {
    color: colors.text,
    fontSize: 12.5,
    lineHeight: 18,
    fontFamily: mono,
  },
  toolCard: {
    backgroundColor: 'transparent',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: space.md,
    paddingVertical: space.sm + 2,
    gap: 3,
  },
  toolHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toolName: {
    ...type.monoSm,
    color: colors.textDim,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  toolInput: {
    ...type.monoSm,
    color: colors.textFaint,
  },
  toolOutput: {
    color: colors.textDim,
    fontSize: 11.5,
    lineHeight: 16,
    fontFamily: mono,
  },
  noticeRow: { alignItems: 'center', paddingVertical: space.md },
  noticeText: { color: colors.textDim, ...type.monoSm },
  toolRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.sm,
    paddingVertical: 5,
  },
  toolIcon: { width: 16, alignItems: 'center' },
  toolTitle: { color: colors.textDim, ...type.bodySm },
  toolDetail: { color: colors.textFaint, ...type.bodySm, flexShrink: 1 },
  toolDetailMono: { ...type.monoSm },
  toolOutputBox: {
    marginTop: space.xs,
    marginLeft: 24,
    paddingHorizontal: space.md,
    paddingVertical: space.sm,
    backgroundColor: colors.surfaceRaised,
    borderRadius: radius.sm,
    borderColor: colors.border,
    borderWidth: StyleSheet.hairlineWidth,
  },
  toolOutputText: { color: colors.textDim, ...type.monoSm },
  toolMeta: { color: colors.textFaint, ...type.monoSm, marginTop: space.xs },
  toolInputProse: { color: colors.textDim, ...type.bodySm },
  queuedNote: { color: colors.textDim, ...type.monoSm, marginBottom: space.sm },
  denialPill: {
    alignSelf: 'flex-start',
    marginHorizontal: 14,
    marginVertical: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: 'rgba(229, 84, 74, 0.12)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(229, 84, 74, 0.5)',
  },
  denialText: {
    color: colors.red,
    fontSize: 12,
  },
  approvalCard: {
    backgroundColor: 'rgba(229, 165, 58, 0.06)',
    borderWidth: 1,
    borderColor: colors.amber,
    borderRadius: 8,
    padding: 10,
    gap: 6,
  },
  cardResolved: {
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  approvalTitle: {
    color: colors.amber,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 6,
    alignItems: 'center',
  },
  approveButton: {
    backgroundColor: colors.green,
  },
  denyButton: {
    backgroundColor: colors.red,
  },
  actionLabel: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  questionCard: {
    backgroundColor: 'rgba(229, 165, 58, 0.04)',
    borderWidth: 1,
    borderColor: colors.amber,
    borderRadius: 8,
    padding: 10,
    gap: 8,
  },
  questionHeader: {
    color: colors.amber,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  questionBlock: {
    gap: 4,
  },
  questionSubHeader: {
    color: colors.textDim,
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  questionText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  questionHint: {
    color: colors.textFaint,
    fontSize: 11,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  optionRowSelected: {
    borderColor: colors.accent,
    backgroundColor: 'rgba(79, 142, 247, 0.1)',
  },
  optionRowDimmed: {
    opacity: 0.4,
  },
  optionNum: {
    width: 22,
    height: 22,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceRaised,
  },
  optionNumSelected: {
    backgroundColor: 'rgba(79, 142, 247, 0.25)',
  },
  optionNumText: {
    color: colors.textDim,
    fontSize: 12,
    fontFamily: mono,
  },
  optionNumTextSelected: {
    color: colors.accent,
  },
  optionBody: {
    flex: 1,
    gap: 1,
  },
  optionLabel: {
    color: colors.text,
    fontSize: 13.5,
    fontWeight: '500',
  },
  optionDesc: {
    color: colors.textDim,
    fontSize: 12,
  },
  optionCheck: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: '700',
  },
  submitButton: {
    backgroundColor: colors.accent,
    marginTop: 2,
  },
  submitDisabled: {
    opacity: 0.4,
  },
  planCard: {
    borderWidth: 1,
    borderColor: colors.accent,
    borderRadius: 8,
    padding: 10,
    gap: 8,
    backgroundColor: 'rgba(79, 142, 247, 0.05)',
  },
  planHeader: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  implementButton: {
    backgroundColor: colors.accent,
  },
  iterateButton: {
    backgroundColor: colors.surfaceRaised,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  iterateLabel: {
    color: colors.textDim,
    fontSize: 13,
    fontWeight: '600',
  },
  fileEditCard: {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    gap: 4,
  },
  fileEditTitle: {
    color: colors.text,
    fontSize: 13,
    fontFamily: mono,
  },
  fileEditMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addedText: {
    color: colors.green,
    fontSize: 12,
    fontFamily: mono,
  },
  removedText: {
    color: colors.red,
    fontSize: 12,
    fontFamily: mono,
  },
  fileEditApplied: {
    color: colors.textFaint,
    fontSize: 11,
  },
  errorText: {
    marginHorizontal: 14,
    marginVertical: 4,
    color: colors.red,
    fontSize: 13,
  },
  pressed: {
    opacity: 0.6,
  },
  modelChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    maxWidth: 140,
  },
  modelChipText: {
    color: colors.textDim,
    fontSize: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    paddingVertical: 12,
    paddingHorizontal: 8,
    maxHeight: '70%',
  },
  modalTitle: {
    color: colors.textDim,
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  modelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 11,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  modelRowText: {
    color: colors.text,
    fontSize: 15,
    flex: 1,
  },
  modelRowTextActive: {
    color: colors.accent,
    fontWeight: '600',
  },
  modelRowMark: {
    color: colors.textFaint,
    fontSize: 11,
    marginLeft: 10,
  },
  composer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingTop: 8,
    gap: 8,
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.sm,
  },
  controlsScroller: {
    flex: 1,
    minHeight: 40,
  },
  controlsContent: {
    gap: space.sm,
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  controlsActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: space.sm,
  },
  // Owns the border and fill so the send button can nest flush inside it: the
  // small right padding is what makes the circle sit against the edge.
  inputSurface: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingLeft: 18,
    paddingRight: 5,
    paddingVertical: 5,
    borderRadius: radius.lg,
    backgroundColor: colors.bg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  input: {
    flex: 1,
    minHeight: 36,
    maxHeight: 160,
    paddingHorizontal: 4,
    paddingVertical: 8,
    color: colors.text,
    fontSize: 15,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accent,
  },
  sendButtonDisabled: {
    backgroundColor: colors.surfaceRaised,
    opacity: 0.55,
  },
  stopButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.red,
  },
})
