import { describe, expect, it } from 'vitest'
import {
  isSyntheticOnlyUserText,
  splitSyntheticUserText,
  syntheticPartDetail,
  syntheticPartLabel,
  syntheticPartTone,
  userTypedText,
} from '../../src/shared/synthetic-message'
import { visibleUserMessageText } from '../../src/shared/provider-events'
import { generateTitle } from '../../src/shared/auto-title'

// Real transcript samples, ids and paths redacted.
const FAILED = `<task-notification>
<task-id>b000000aa</task-id>
<tool-use-id>toolu_01REDACTED</tool-use-id>
<output-file>/private/tmp/claude-501/-Users-me-proj/0000/tasks/b000000aa.output</output-file>
<status>failed</status>
<summary>Background command "Wait for the first extra-account job to finish" failed with exit code 144</summary>
</task-notification>`

const COMPLETED = `<task-notification>
<task-id>b000000bb</task-id>
<tool-use-id>toolu_01REDACTED</tool-use-id>
<output-file>/private/tmp/claude-501/x/tasks/b000000bb.output</output-file>
<status>completed</status>
<summary>Background command "Regenerate all three packets with new format" completed (exit code 0)</summary>
</task-notification>`

const PREAMBLE = `[SYSTEM NOTIFICATION - NOT USER INPUT]
This is an automated background-task event, NOT a message from the user.
Do NOT interpret this as user acknowledgement.

`

describe('splitSyntheticUserText', () => {
  it('extracts a failed task notification', () => {
    const split = splitSyntheticUserText(FAILED)
    expect(split).toEqual({
      parts: [{
        kind: 'task-notification',
        status: 'failed',
        summary: 'Background command "Wait for the first extra-account job to finish" failed with exit code 144',
        taskId: 'b000000aa',
        outputFile: '/private/tmp/claude-501/-Users-me-proj/0000/tasks/b000000aa.output',
      }],
      userText: '',
    })
    const part = split!.parts[0]
    expect(syntheticPartLabel(part)).toBe('Background task failed: Wait for the first extra-account job to finish (exit 144)')
    expect(syntheticPartTone(part)).toBe('error')
    expect(syntheticPartDetail(part)).toContain('Task: b000000aa')
  })

  it('omits a zero exit code and colours completion', () => {
    const part = splitSyntheticUserText(COMPLETED)!.parts[0]
    expect(syntheticPartLabel(part)).toBe('Background task completed: Regenerate all three packets with new format')
    expect(syntheticPartTone(part)).toBe('ok')
  })

  it('keeps real user text typed after a notification', () => {
    const split = splitSyntheticUserText(`${FAILED}\nContinue from where you left off.`)
    expect(split?.parts).toHaveLength(1)
    expect(split?.userText).toBe('Continue from where you left off.')
  })

  it('splits back-to-back notifications and a notification preamble', () => {
    const split = splitSyntheticUserText(`${PREAMBLE}${FAILED}\n${COMPLETED}`)
    expect(split?.parts.map((part) => part.kind === 'task-notification' && part.status)).toEqual(['failed', 'completed'])
    expect(split?.userText).toBe('')
  })

  it('classifies interrupts and local command output', () => {
    expect(splitSyntheticUserText('[Request interrupted by user]')?.parts).toEqual([{ kind: 'interrupted', duringToolUse: false }])
    expect(splitSyntheticUserText('[Request interrupted by user for tool use]')?.parts).toEqual([{ kind: 'interrupted', duringToolUse: true }])
    expect(splitSyntheticUserText('<local-command-stdout>Set model to claude-fable-5</local-command-stdout>')?.parts)
      .toEqual([{ kind: 'command-output', text: 'Set model to claude-fable-5', isError: false }])
    expect(splitSyntheticUserText('<local-command-stdout></local-command-stdout>')).toEqual({ parts: [], userText: '' })
  })

  it('drops pure context blocks without a row', () => {
    const caveat = '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'
    expect(splitSyntheticUserText(caveat)).toEqual({ parts: [], userText: '' })
    const env = '<environment_context>\n  <cwd>/repo</cwd>\n</environment_context>\nfix the build'
    expect(splitSyntheticUserText(env)).toEqual({ parts: [], userText: 'fix the build' })
    const goal = '<codex_internal_context source="goal">\nContinue working toward the active thread goal.\n</codex_internal_context>'
    expect(isSyntheticOnlyUserText(goal)).toBe(true)
  })

  it('leaves real messages alone, including ones that mention a marker', () => {
    expect(splitSyntheticUserText('please look at this')).toBeNull()
    expect(splitSyntheticUserText('What does <task-notification> mean?')).toBeNull()
    expect(splitSyntheticUserText('<task-notification> without a close tag')).toBeNull()
    expect(userTypedText('fix it')).toBe('fix it')
  })
})

describe('consumers', () => {
  it('visibleUserMessageText keeps row-worthy blocks and drops context-only ones', () => {
    expect(visibleUserMessageText(FAILED)).toBe(FAILED)
    expect(visibleUserMessageText('<local-command-caveat>x</local-command-caveat>')).toBeNull()
  })

  it('a notification never becomes a title', () => {
    expect(generateTitle(userTypedText(`${FAILED}\nship it`))).toBe('ship it')
    expect(userTypedText(FAILED)).toBe('')
  })
})
