import { afterEach, describe, expect, it } from 'vitest'
import Database from 'better-sqlite3'
import { mkdirSync, mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { closeDb, getDb } from '../../src/main/db/database'

const previousDataDir = process.env.SWITCHBOARD_DATA_DIR
const scratch: string[] = []

afterEach(() => {
  closeDb()
  if (previousDataDir === undefined) delete process.env.SWITCHBOARD_DATA_DIR
  else process.env.SWITCHBOARD_DATA_DIR = previousDataDir
  for (const path of scratch.splice(0)) rmSync(path, { recursive: true, force: true })
})

describe('v0.8.35 database upgrade', () => {
  it('preserves representative work and remains idempotent across relaunch', () => {
    const root = mkdtempSync(join(tmpdir(), 'sb-v0835-upgrade-'))
    scratch.push(root)
    process.env.SWITCHBOARD_DATA_DIR = root
    const dataDir = join(root, 'data')
    mkdirSync(dataDir, { recursive: true })
    createV0835Fixture(join(dataDir, 'switchboard.db'))

    let upgraded = getDb()
    assertFixtureSurvived(upgraded)
    expect(upgraded.pragma('foreign_key_check')).toEqual([])
    expect(upgraded.pragma('integrity_check')).toEqual([{ integrity_check: 'ok' }])
    expect(tableNames(upgraded)).toEqual(expect.arrayContaining([
      'mobile_turn_acceptances',
      'worktree_creations',
      'provider_instances',
      'messages',
    ]))
    const acceptanceSql = upgraded.prepare(`
      SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'mobile_turn_acceptances'
    `).get() as { sql: string }
    expect(acceptanceSql.sql).toContain("'abandoned'")

    closeDb()
    upgraded = getDb()
    assertFixtureSurvived(upgraded)
    expect(upgraded.pragma('foreign_key_check')).toEqual([])
    expect(upgraded.pragma('integrity_check')).toEqual([{ integrity_check: 'ok' }])
  })
})

function assertFixtureSurvived(db: Database.Database): void {
  expect(db.prepare('SELECT path, name, sort_order FROM projects WHERE path = ?')
    .get('/fixture/project')).toEqual({
    path: '/fixture/project',
    name: 'Fixture project',
    sort_order: 3,
  })
  expect(db.prepare(`
    SELECT title, session_id, archived, runtime_mode
      FROM conversations WHERE id = 'fixture-thread'
  `).get()).toEqual({
    title: 'Upgrade fixture',
    session_id: 'native-session',
    archived: 1,
    runtime_mode: 'sandbox',
  })
  expect(db.prepare(`
    SELECT content, display_body, images FROM messages WHERE id = 'fixture-message'
  `).get()).toEqual({
    content: 'provider text',
    display_body: 'visible text',
    images: JSON.stringify([{ url: 'data:image/png;base64,AAA', mimeType: 'image/png' }]),
  })
  expect(db.prepare("SELECT value FROM settings WHERE key = 'fixture-setting'").get())
    .toEqual({ value: 'preserved' })
}

function tableNames(db: Database.Database): string[] {
  return (db.prepare(`
    SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name
  `).all() as Array<{ name: string }>).map((row) => row.name)
}

/** Schema snapshot generated by running the published v0.8.35 database
 * initializer in an isolated SWITCHBOARD_DATA_DIR. No live profile is read. */
function createV0835Fixture(path: string): void {
  const db = new Database(path)
  db.pragma('foreign_keys = ON')
  db.exec(`
    CREATE TABLE project_workspaces (
      id TEXT PRIMARY KEY, name TEXT NOT NULL, color TEXT,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000)
    );
    CREATE TABLE projects (
      path TEXT PRIMARY KEY, name TEXT NOT NULL,
      added_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      sort_order INTEGER NOT NULL DEFAULT 0,
      workspace_id TEXT REFERENCES project_workspaces(id) ON DELETE SET NULL
    );
    CREATE TABLE conversations (
      id TEXT PRIMARY KEY, project_path TEXT NOT NULL,
      agent_type TEXT NOT NULL DEFAULT 'claude-code', session_id TEXT,
      title TEXT NOT NULL DEFAULT 'New conversation',
      created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      archived INTEGER NOT NULL DEFAULT 0, runtime_mode TEXT,
      parent_conversation_id TEXT, forked_at_message_id TEXT,
      worktree_path TEXT, worktree_branch TEXT, last_read_at INTEGER,
      sidebar_role TEXT, provider_instance_id TEXT, model TEXT,
      pending_handoff_from TEXT,
      FOREIGN KEY (project_path) REFERENCES projects(path) ON DELETE CASCADE
    );
    CREATE TABLE messages (
      id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, role TEXT NOT NULL,
      content TEXT NOT NULL DEFAULT '', tool_calls TEXT, images TEXT,
      timestamp INTEGER NOT NULL, display_body TEXT, pills_meta TEXT,
      FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
    );
    CREATE VIRTUAL TABLE messages_fts USING fts5(
      content, conversation_id UNINDEXED, role UNINDEXED, tokenize='unicode61'
    );
    CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
    CREATE TABLE session_layouts (
      session_id TEXT PRIMARY KEY, layout_json TEXT NOT NULL,
      updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      launch_config_name TEXT
    );
    CREATE TABLE thread_sessions (
      claude_session_id TEXT PRIMARY KEY, thread_id TEXT NOT NULL,
      recorded_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000)
    );
    CREATE TABLE conversation_segments (
      id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL, provider TEXT NOT NULL,
      provider_session_id TEXT NOT NULL, provider_instance_id TEXT,
      ordinal INTEGER NOT NULL,
      created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      UNIQUE(conversation_id, provider, provider_session_id)
    );
    CREATE TABLE kanban_cards (
      id TEXT PRIMARY KEY, project_path TEXT NOT NULL, title TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '', tags TEXT NOT NULL DEFAULT '[]',
      status TEXT NOT NULL DEFAULT 'backlog', cost_cap_usd REAL, cost_used_usd REAL,
      runtime_mode TEXT NOT NULL DEFAULT 'accept-edits', conversation_id TEXT,
      worktree_path TEXT, worktree_branch TEXT,
      created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000), completed_at INTEGER,
      FOREIGN KEY (project_path) REFERENCES projects(path) ON DELETE CASCADE
    );
    CREATE TABLE bookmarks (
      id TEXT PRIMARY KEY, session_id TEXT NOT NULL,
      project_path TEXT NOT NULL DEFAULT '', session_title TEXT NOT NULL DEFAULT '',
      agent_type TEXT NOT NULL DEFAULT 'claude-code', message_role TEXT NOT NULL,
      content_excerpt TEXT NOT NULL, message_timestamp INTEGER NOT NULL,
      saved_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      UNIQUE(session_id, message_timestamp)
    );
    CREATE TABLE provider_instances (
      id TEXT PRIMARY KEY, agent_type TEXT NOT NULL, display_name TEXT NOT NULL,
      accent_color TEXT, auth_mode TEXT NOT NULL DEFAULT 'env', env_encrypted BLOB,
      oauth_dir TEXT, config_json TEXT, enabled INTEGER NOT NULL DEFAULT 1,
      created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
      updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000), env_keys TEXT
    );
    CREATE TABLE machines (
      id TEXT PRIMARY KEY, name TEXT NOT NULL, ssh_alias TEXT, ssh_host TEXT NOT NULL,
      ssh_user TEXT, ssh_port INTEGER NOT NULL DEFAULT 22, remote_user TEXT,
      transport_kind TEXT NOT NULL DEFAULT 'ssh', iap_instance TEXT,
      iap_project TEXT, iap_zone TEXT, sort_order INTEGER NOT NULL DEFAULT 0,
      created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL
    );
    CREATE TABLE machine_snapshots (
      machine_id TEXT PRIMARY KEY, data TEXT NOT NULL, synced_at INTEGER NOT NULL
    );
    CREATE INDEX idx_messages_conversation ON messages(conversation_id, timestamp);
    CREATE INDEX idx_conversations_project ON conversations(project_path, updated_at DESC);
    CREATE INDEX idx_conversations_archived ON conversations(archived) WHERE archived = 1;
    CREATE INDEX idx_conversations_sidebar_roots
      ON conversations(project_path, updated_at DESC)
      WHERE sidebar_role = 'managed' AND archived = 0;
    CREATE INDEX idx_projects_workspace ON projects(workspace_id);
    CREATE INDEX idx_projects_workspace_order ON projects(workspace_id, sort_order);
    CREATE INDEX idx_thread_sessions_thread ON thread_sessions(thread_id);
    CREATE INDEX idx_conversation_segments_order ON conversation_segments(conversation_id, ordinal);
    CREATE INDEX idx_conversation_segments_resume
      ON conversation_segments(conversation_id, provider, provider_instance_id, ordinal DESC);
    CREATE INDEX idx_kanban_project_status ON kanban_cards(project_path, status, updated_at DESC);
    CREATE INDEX idx_bookmarks_saved_at ON bookmarks(saved_at DESC);
    CREATE INDEX idx_provider_instances_agent ON provider_instances(agent_type);
    CREATE INDEX idx_machines_sort ON machines(sort_order);
  `)
  db.prepare('INSERT INTO projects(path, name, added_at, sort_order) VALUES (?, ?, ?, ?)')
    .run('/fixture/project', 'Fixture project', 100, 3)
  db.prepare(`
    INSERT INTO conversations
      (id, project_path, agent_type, session_id, title, created_at, updated_at, archived, runtime_mode)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    'fixture-thread', '/fixture/project', 'claude-code', 'native-session',
    'Upgrade fixture', 101, 102, 1, 'sandbox',
  )
  db.prepare(`
    INSERT INTO messages
      (id, conversation_id, role, content, images, timestamp, display_body, pills_meta)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    'fixture-message', 'fixture-thread', 'user', 'provider text',
    JSON.stringify([{ url: 'data:image/png;base64,AAA', mimeType: 'image/png' }]),
    103, 'visible text', JSON.stringify({}),
  )
  db.prepare('INSERT INTO settings(key, value) VALUES (?, ?)')
    .run('fixture-setting', 'preserved')
  db.close()
}
